/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mygui2;

/**
 *
 * @author chonn
 */
public class MainForm extends javax.swing.JFrame {

    private LoginForm loginForm;
    private ProductForm productForm;
    private ProductDetailForm productDetailForm;
    
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        
        menuProducts.setVisible(false);
        menuLogout.setVisible(false);
        this.setTitle("Inventory by Chonnawee Phiphatkul");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuLogin = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuExit = new javax.swing.JMenuItem();
        menuProducts = new javax.swing.JMenu();
        menuNewProduct = new javax.swing.JMenuItem();
        menuProductList = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        menuLogin.setText("Login");
        menuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoginActionPerformed(evt);
            }
        });
        jMenu1.add(menuLogin);

        menuLogout.setText("Logout");
        jMenu1.add(menuLogout);
        jMenu1.add(jSeparator1);

        menuExit.setText("Exit");
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        menuProducts.setText("Products");

        menuNewProduct.setText("New Item");
        menuNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewProductActionPerformed(evt);
            }
        });
        menuProducts.add(menuNewProduct);

        menuProductList.setText("Product List");
        menuProductList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductListActionPerformed(evt);
            }
        });
        menuProducts.add(menuProductList);

        jMenuBar1.add(menuProducts);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoginActionPerformed
        if (loginForm == null) {
            loginForm = new LoginForm(
               new LoginFormCallback() {
                @Override
                public void userLogin(LoginForm form, String username, String password) {
                    for (User user : GlobalVar.users) {
                        if (user.authenticate(username, password)) {
                            GlobalVar.currentUser = user;
                            loginForm.setVisible(false);
                            menuProducts.setVisible(true);
                            menuLogin.setVisible(false);
                            menuLogout.setVisible(true);
                            break;
                        }
                    }
                }
               }
            ); 
            jDesktopPane1.add(loginForm);
        }
        loginForm.setVisible(true);
    }//GEN-LAST:event_menuLoginActionPerformed

    private void menuProductListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductListActionPerformed
        if (productForm == null) {
            productForm = new ProductForm();
            jDesktopPane1.add(productForm);
        }
        
        productForm.setVisible(true);
    }//GEN-LAST:event_menuProductListActionPerformed

    private void menuNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewProductActionPerformed
        if (productDetailForm == null) {
            productDetailForm = new ProductDetailForm(null);
            jDesktopPane1.add(productDetailForm);
        }
        
        productDetailForm.setVisible(true);
    }//GEN-LAST:event_menuNewProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuLogin;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenuItem menuNewProduct;
    private javax.swing.JMenuItem menuProductList;
    private javax.swing.JMenu menuProducts;
    // End of variables declaration//GEN-END:variables
}